App\Output\Outputs\UserOutput:
  properties:
        username:
            - NotBlank: ~
            - Length:
                min: 2
                max: 30
        password:
            - NotBlank: ~
            - Length:
                min: 8
        